services:
  postgres:
    image: postgres:16-alpine
    container_name: ops-api-postgres
    environment:
      POSTGRES_USER: ops
      POSTGRES_PASSWORD: ops
      POSTGRES_DB: opsdb
    ports:
      - "5433:5432"
    volumes:
      - ops_api_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ops -d opsdb"]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: ../app
      dockerfile: Dockerfile
    image: ops-api:local
    container_name: ops-api-app
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/opsdb
      SPRING_DATASOURCE_USERNAME: ops
      SPRING_DATASOURCE_PASSWORD: ops
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  ops_api_pgdata:
